/** 解説文に出やすい都市・制度の座標辞書（試験用） */
export type PlaceEntry = {
  id: string;
  label: string;
  aliases: string[];
  lat: number;
  lng: number;
  kind: "city" | "institution" | "event";
};

export const PLACE_GAZETTEER: PlaceEntry[] = [
  {
    id: "new-york",
    label: "New York",
    aliases: ["New York", "NYC", "Brooklyn"],
    lat: 40.7128,
    lng: -74.006,
    kind: "city",
  },
  {
    id: "london",
    label: "London",
    aliases: ["London"],
    lat: 51.5074,
    lng: -0.1278,
    kind: "city",
  },
  {
    id: "paris",
    label: "Paris",
    aliases: ["Paris"],
    lat: 48.8566,
    lng: 2.3522,
    kind: "city",
  },
  {
    id: "berlin",
    label: "Berlin",
    aliases: ["Berlin"],
    lat: 52.52,
    lng: 13.405,
    kind: "city",
  },
  {
    id: "los-angeles",
    label: "Los Angeles",
    aliases: ["Los Angeles"],
    lat: 34.0522,
    lng: -118.2437,
    kind: "city",
  },
  {
    id: "tokyo",
    label: "Tokyo",
    aliases: ["Tokyo"],
    lat: 35.6762,
    lng: 139.6503,
    kind: "city",
  },
  {
    id: "hong-kong",
    label: "Hong Kong",
    aliases: ["Hong Kong"],
    lat: 22.3193,
    lng: 114.1694,
    kind: "city",
  },
  {
    id: "shanghai",
    label: "Shanghai",
    aliases: ["Shanghai"],
    lat: 31.2304,
    lng: 121.4737,
    kind: "city",
  },
  {
    id: "beijing",
    label: "Beijing",
    aliases: ["Beijing"],
    lat: 39.9042,
    lng: 116.4074,
    kind: "city",
  },
  {
    id: "seoul",
    label: "Seoul",
    aliases: ["Seoul"],
    lat: 37.5665,
    lng: 126.978,
    kind: "city",
  },
  {
    id: "venice",
    label: "Venice",
    aliases: ["Venice", "Venetian"],
    lat: 45.4408,
    lng: 12.3155,
    kind: "city",
  },
  {
    id: "basel",
    label: "Basel",
    aliases: ["Basel", "Art Basel"],
    lat: 47.5596,
    lng: 7.5886,
    kind: "city",
  },
  {
    id: "doha",
    label: "Doha",
    aliases: ["Doha", "Qatar"],
    lat: 25.2854,
    lng: 51.531,
    kind: "city",
  },
  {
    id: "dubai",
    label: "Dubai",
    aliases: ["Dubai"],
    lat: 25.2048,
    lng: 55.2708,
    kind: "city",
  },
  {
    id: "amsterdam",
    label: "Amsterdam",
    aliases: ["Amsterdam"],
    lat: 52.3676,
    lng: 4.9041,
    kind: "city",
  },
  {
    id: "milan",
    label: "Milan",
    aliases: ["Milan", "Milano"],
    lat: 45.4642,
    lng: 9.19,
    kind: "city",
  },
  {
    id: "vienna",
    label: "Vienna",
    aliases: ["Vienna"],
    lat: 48.2082,
    lng: 16.3738,
    kind: "city",
  },
  {
    id: "sao-paulo",
    label: "São Paulo",
    aliases: ["São Paulo", "Sao Paulo"],
    lat: -23.5505,
    lng: -46.6333,
    kind: "city",
  },
  {
    id: "mexico-city",
    label: "Mexico City",
    aliases: ["Mexico City"],
    lat: 19.4326,
    lng: -99.1332,
    kind: "city",
  },
  {
    id: "cairo",
    label: "Cairo",
    aliases: ["Cairo", "Alexandria"],
    lat: 30.0444,
    lng: 31.2357,
    kind: "city",
  },
  {
    id: "lagos",
    label: "Lagos",
    aliases: ["Lagos"],
    lat: 6.5244,
    lng: 3.3792,
    kind: "city",
  },
  {
    id: "johannesburg",
    label: "Johannesburg",
    aliases: ["Johannesburg"],
    lat: -26.2041,
    lng: 28.0473,
    kind: "city",
  },
  {
    id: "mumbai",
    label: "Mumbai",
    aliases: ["Mumbai", "Bombay"],
    lat: 19.076,
    lng: 72.8777,
    kind: "city",
  },
  {
    id: "singapore",
    label: "Singapore",
    aliases: ["Singapore"],
    lat: 1.3521,
    lng: 103.8198,
    kind: "city",
  },
  {
    id: "sydney",
    label: "Sydney",
    aliases: ["Sydney"],
    lat: -33.8688,
    lng: 151.2093,
    kind: "city",
  },
  {
    id: "taipei",
    label: "Taipei",
    aliases: ["Taipei"],
    lat: 25.033,
    lng: 121.5654,
    kind: "city",
  },
  {
    id: "istanbul",
    label: "Istanbul",
    aliases: ["Istanbul"],
    lat: 41.0082,
    lng: 28.9784,
    kind: "city",
  },
  {
    id: "athens",
    label: "Athens",
    aliases: ["Athens"],
    lat: 37.9838,
    lng: 23.7275,
    kind: "city",
  },
  {
    id: "ramallah",
    label: "Ramallah",
    aliases: ["Ramallah", "West Bank", "Gaza"],
    lat: 31.9038,
    lng: 35.2034,
    kind: "city",
  },
  {
    id: "kassel",
    label: "Kassel (Documenta)",
    aliases: ["Documenta", "Kassel"],
    lat: 51.3127,
    lng: 9.4797,
    kind: "event",
  },
  {
    id: "moma",
    label: "MoMA",
    aliases: ["MoMA", "Museum of Modern Art"],
    lat: 40.7614,
    lng: -73.9776,
    kind: "institution",
  },
  {
    id: "tate",
    label: "Tate",
    aliases: ["Tate Modern", "Tate Britain", "Tate "],
    lat: 51.5076,
    lng: -0.0994,
    kind: "institution",
  },
  {
    id: "guggenheim",
    label: "Guggenheim",
    aliases: ["Guggenheim"],
    lat: 40.7829,
    lng: -73.959,
    kind: "institution",
  },
  {
    id: "whitney",
    label: "Whitney",
    aliases: ["Whitney Museum", "Whitney "],
    lat: 40.7396,
    lng: -74.0089,
    kind: "institution",
  },
  {
    id: "centre-pompidou",
    label: "Centre Pompidou",
    aliases: ["Centre Pompidou", "Pompidou"],
    lat: 48.8606,
    lng: 2.3522,
    kind: "institution",
  },
];
